# Generated by Django 2.1 on 2022-04-04 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 17, 53, 6, 379432, tzinfo=utc)),
        ),
    ]
